### ISSUE TITLE
Other player's dart not show in right position

### ISSUE THREAD

**Issue by shanlee870502** [a129123659/dARt#6]
Already check the game data from sending and receiving thread, both data are the same.
Please check the function `onOtherPlayersDartHitsDartboard()` and take a closer look , thank you.
https://github.com/a129123659/dARt/blob/e2d34123a747476540db871b40cbc77bdc38d924/app/src/main/java/game/Game.kt#L53-L59

Good luck 🙏

**Comment by a129123659** [comment]
This is **the order you send to server, which is ```X_r, Y_r, Z_r, W_r, X_t, Y_t, Z_t```**, where ```_r, _t``` represent rotation and translation respectively

https://github.com/a129123659/dARt/blob/e3b5d8dbaca51707acc721d5e9479f8f279f6d56/app/src/main/java/connection/SocketConnection.java#L88-L93

And **this is the how you interpret the incomming array from the server, which is ```X_t, Y_t, Z_t, X_r, Y_r, Z_r, W_r```**.
What an *outstanding* move you've done there.

https://github.com/a129123659/dARt/blob/e3b5d8dbaca51707acc721d5e9479f8f279f6d56/app/src/main/java/connection/SocketConnection.java#L210-L211

> Already check the game data from sending and receiving thread, both data are the same.

**EXACTLY! CAN'T AGREE YOU MORE**
Same data with wrong approach to interpret the data then **PASS THIS WRONG DATA TO ME**. Thank you! I'm very grateful.

**Comment by shanlee870502** [comment]
How ironic it is! Even if I send in the right order, what you've done here is absolutely incredible.
https://github.com/a129123659/dARt/blob/885ab0c2e4cb89a2e3c3aef70cb4a9b351c8ade9/app/src/main/java/game/Game.kt#L37-L38
You send the dartPoseInWorld data to me, which means you send the coordinate that  **HAVEN'T SHOOT YET**
That's one of the reason why other player's dart not show in right position...
--No wonder Roast Jie sounds like your Chinese name--

**Comment by shanlee870502** [comment]
885ab0c2e4cb89a2e3c3aef70cb4a9b351c8ade9

**Comment by shanlee870502** [comment]
b28c790f9a3e6349eaeb7a40e72aeeec51bf768c
